'use client';

import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Fingerprint, Activity, Zap, Shield, BookOpen, Send, Atom, Sparkles, Cpu, Globe, MessageSquare, X, FileText, GitGraph, Hash, Printer, Microscope } from 'lucide-react';

// --- 1. 星空特效组件 ---
const Starfield = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const setSize = () => {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    };
    setSize();
    window.addEventListener('resize', setSize);

    const particles: {x: number, y: number, size: number, speed: number, opacity: number}[] = [];
    const count = 60; 

    for (let i = 0; i < count; i++) {
      particles.push({
        x: Math.random() * canvas.width,
        y: Math.random() * canvas.height,
        size: Math.random() * 2,
        speed: Math.random() * 0.5 + 0.1,
        opacity: Math.random() * 0.8 + 0.2
      });
    }

    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      particles.forEach(p => {
        p.y -= p.speed;
        if (p.y < 0) p.y = canvas.height;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
        ctx.fillStyle = `rgba(103, 232, 249, ${p.opacity})`;
        ctx.fill();
      });
      requestAnimationFrame(animate);
    };
    animate();

    return () => window.removeEventListener('resize', setSize);
  }, []);

  return <canvas ref={canvasRef} className="absolute inset-0 z-0 pointer-events-none opacity-60" />;
};

// --- 2. 主页面组件 ---
export default function EntropyPage() {
  const [mounted, setMounted] = useState(false);
  const [status, setStatus] = useState('idle');
  const [result, setResult] = useState<any>(null);
  const [showManual, setShowManual] = useState(false);

  // 输入状态
  const [q1, setQ1] = useState('');
  const [q2, setQ2] = useState('');
  const [q3, setQ3] = useState('');
  const [supplement, setSupplement] = useState('');

  useEffect(() => { setMounted(true); }, []);

  // --- 核心功能：生成打印版 PDF ---
  const handlePrint = () => {
    const printContent = `
      <html>
        <head>
          <title>TDFT 技术白皮书 - 打印版</title>
          <style>
            body { font-family: "Times New Roman", "Songti SC", serif; padding: 40px; color: #000; line-height: 1.8; max-width: 800px; margin: 0 auto; }
            h1 { font-size: 24px; text-align: center; margin-bottom: 10px; font-weight: bold; }
            .subtitle { text-align: center; font-size: 14px; color: #666; font-style: italic; margin-bottom: 40px; border-bottom: 1px solid #000; padding-bottom: 20px; }
            h2 { font-size: 18px; margin-top: 30px; border-left: 4px solid #000; padding-left: 10px; font-weight: bold; }
            h3 { font-size: 16px; margin-top: 20px; font-weight: bold; }
            p { margin-bottom: 15px; text-align: justify; }
            .formula { background: #f5f5f5; padding: 15px; text-align: center; font-family: "Courier New", monospace; margin: 20px 0; border: 1px solid #ddd; }
            .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 20px; }
            @media print { .no-print { display: none; } }
          </style>
        </head>
        <body>
          <h1>热力学决策场论 (TDFT)</h1>
          <div class="subtitle">Thermodynamic Decision Field Theory: A Non-Equilibrium Phase Transition Model</div>
          
          <h2>01. 摘要 (Abstract)</h2>
          <p>传统决策模型难以有效处理高熵环境下的非线性动态博弈。本文提出热力学决策场论 (TDFT)，将决策过程建模为相空间中的能量跃迁。通过引入熵 (Entropy)、激活能 (Activation Energy) 和鲁棒性 (Robustness) 三个核心序参量，定量描述决策系统的混乱度、势能壁垒及抗扰动能力。</p>

          <h2>02. 第一定律：决策熵 (Decision Entropy)</h2>
          <div class="formula">S = -kB Σ pi ln(pi)</div>
          <p><strong>定义：</strong>系统的混乱程度与迷茫指数。</p>
          <p><strong>原理：</strong>决策系统的首要任务是“降熵”。当信息模糊、变量过多时，系统进入高熵态 (High Entropy)，表现为认知过载与行动瘫痪。此时任何强制行动都将转化为系统的内耗热量，而非有效功。</p>

          <h2>03. 第二定律：激活能 (Activation Energy)</h2>
          <div class="formula">k = A · e^(-Ea/RT)</div>
          <p><strong>定义：</strong>改变现状所需的能量门槛。</p>
          <p><strong>原理：</strong>任何现状的改变（如创业、转型）都视为一次“化学反应”。Ea 是打破旧平衡所需的最小能量阈值（资金、认知、人脉）。若势能壁垒远高于能量储备，强行跃迁将导致系统耗散崩溃。</p>

          <h2>04. 第三定律：鲁棒性 (Robustness)</h2>
          <p><strong>定义：</strong>路径坍缩成功的可能性与抗风险能力。</p>
          <p><strong>原理：</strong>低鲁棒性系统处于亚稳态 (Metastable)，微小的扰动（黑天鹅事件）即可引发灾难性相变。最优解往往不是收益最大化，而是寻找“低熵-低能耗-高稳态”的吸引子路径 (Attractor Path)。</p>

          <div class="footer">
            Generated by TDFT System v9.0 | Designed by TDFT Research Lab © 2025
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
    }
  };

  const startAnalysis = async () => {
    if (!q1.trim() && !q2.trim() && !q3.trim()) {
      alert("⚠️ 请输入内容");
      return;
    }
    setStatus('analyzing');
    const combinedInput = `【现状】：${q1}\n【选项】：${q2}\n【边界】：${q3}`;
    await fetchAnalysis(combinedInput, null);
  };

  const submitSupplement = async () => {
    if (!supplement.trim()) return;
    setStatus('analyzing');
    await fetchAnalysis(supplement, `【现状】：${q1}\n【选项】：${q2}\n【边界】：${q3}`);
    setSupplement('');
  };

  const fetchAnalysis = async (input: string, context: string | null) => {
    try {
      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userQuestion: input, context: context }),
      });
      if (!res.ok) throw new Error('Failed');
      const data = await res.json();
      setResult(data);
      setStatus('result');
    } catch (error) {
      console.error(error);
      alert("⚠️ 网络错误，请检查 API Key");
      setStatus('idle');
    }
  };

  if (!mounted) return <div className="min-h-screen bg-black" />;

  const getProbabilityColor = (score: number) => {
    if (score >= 75) return 'bg-emerald-500 shadow-[0_0_20px_rgba(16,185,129,0.5)]';
    if (score >= 40) return 'bg-cyan-500 shadow-[0_0_20px_rgba(6,182,212,0.5)]';
    return 'bg-red-500 shadow-[0_0_20px_rgba(239,68,68,0.5)]';
  };

  return (
    <main className="min-h-screen bg-[#050505] text-white font-sans flex flex-col items-center justify-center p-4 relative overflow-hidden">
      
      <Starfield />
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-black/50 to-black z-0 pointer-events-none" />

      {/* 顶部 HUD */}
      <div className="absolute top-6 left-6 flex flex-col gap-1 z-10 opacity-70">
         <div className="flex items-center gap-2 text-[10px] text-cyan-400 font-mono tracking-widest border border-cyan-900/50 px-2 py-1 rounded bg-black/50 backdrop-blur">
            <Globe size={10}/> TDFT-SYSTEM v9.1 PDF
         </div>
      </div>

      <button 
        onClick={() => setShowManual(true)}
        className="fixed top-6 right-6 z-50 flex items-center gap-2 px-4 py-2 rounded-full bg-zinc-900/80 border border-zinc-700/50 text-xs font-bold text-zinc-300 hover:text-white hover:border-cyan-500/50 transition-all backdrop-blur"
      >
        <BookOpen size={14}/> 系统原理
      </button>

      {/* --- 4. 核心功能：学术版原理书弹窗 --- */}
      <AnimatePresence>
        {showManual && (
          <motion.div 
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-0 md:p-6 bg-black/95 backdrop-blur-xl"
            onClick={() => setShowManual(false)}
          >
            <motion.div 
              initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
              className="bg-[#080808] w-full h-full md:h-auto md:max-h-[90vh] md:max-w-4xl md:rounded-2xl border border-zinc-800 shadow-2xl flex flex-col overflow-hidden"
              onClick={e => e.stopPropagation()}
            >
              {/* 弹窗头部 */}
              <div className="flex justify-between items-center p-6 border-b border-zinc-800 bg-zinc-900/50 backdrop-blur shrink-0">
                  <div className="flex items-center gap-3">
                      <div className="p-2 bg-cyan-950/30 rounded border border-cyan-800/30">
                          <FileText className="text-cyan-400" size={20}/>
                      </div>
                      <div>
                          <h2 className="text-lg font-bold text-white tracking-widest">TDFT 技术白皮书</h2>
                          <p className="text-[10px] text-zinc-500 font-mono tracking-wider">DOC. REF: TDFT-2025-WP-ALPHA</p>
                      </div>
                  </div>
                  <div className="flex items-center gap-2">
                      {/* ✨ 新增：PDF 下载按钮 */}
                      <button 
                        onClick={handlePrint}
                        className="flex items-center gap-2 px-4 py-2 bg-white text-black rounded-full font-bold text-xs hover:bg-zinc-200 transition-colors"
                      >
                        <Printer size={14}/> 下载PDF
                      </button>
                      <button onClick={() => setShowManual(false)} className="p-2 hover:bg-zinc-800 rounded-full transition-colors"><X className="text-zinc-400" size={24}/></button>
                  </div>
              </div>

              {/* 弹窗内容 (可滚动) */}
              <div className="flex-grow overflow-y-auto p-6 md:p-12 space-y-12 custom-scrollbar">
                  
                  {/* 标题区 */}
                  <div className="text-center pb-8 border-b border-zinc-800">
                      <h1 className="text-2xl md:text-4xl font-black text-white mb-4 leading-tight">
                          不确定性环境下人类战略决策的<br/>
                          <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-500">非平衡相变模型</span>
                      </h1>
                      <p className="text-sm md:text-base text-zinc-500 font-serif italic">
                          Thermodynamic Decision Field Theory: A Non-Equilibrium Phase Transition Model
                      </p>
                  </div>

                  {/* 摘要 */}
                  <div className="bg-zinc-900/30 border-l-4 border-cyan-500 p-6 rounded-r-lg">
                      <h3 className="text-sm font-bold text-cyan-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                          <Hash size={14}/> Abstract // 摘要
                      </h3>
                      <p className="text-sm md:text-base text-zinc-300 leading-7 text-justify font-light">
                          传统决策模型（如期望效用理论）难以有效处理高熵环境下的非线性动态博弈。本文提出 <strong>热力学决策场论 (TDFT)</strong>，建立在物理学与决策科学的同构性之上。通过引入 <strong>熵 (Entropy)</strong>、<strong>激活能 (Activation Energy)</strong> 和 <strong>鲁棒性 (Robustness)</strong> 三个核心序参量，定量描述决策系统的混乱度、势能壁垒及抗扰动能力。
                      </p>
                  </div>

                  {/* 核心定律 */}
                  <div className="space-y-8">
                      {/* 第一定律 */}
                      <section>
                          <h4 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                              <GitGraph className="text-cyan-500" size={20}/> 第一定律：决策熵 (Decision Entropy)
                          </h4>
                          <div className="bg-black border border-zinc-800 p-4 rounded mb-4 font-mono text-center text-zinc-400 text-sm">
                              S = -k<sub>B</sub> Σ p<sub>i</sub> ln(p<sub>i</sub>)
                          </div>
                          <p className="text-sm md:text-base text-zinc-400 leading-7 text-justify">
                              决策系统的首要任务是“降熵”。当信息模糊、变量过多时，系统进入<strong>高熵态 (High Entropy)</strong>，表现为认知过载与行动瘫痪。此时任何强制行动都将转化为系统的内耗热量，而非有效功。
                          </p>
                      </section>

                      {/* 第二定律 */}
                      <section>
                          <h4 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                              <Zap className="text-purple-500" size={20}/> 第二定律：激活能 (Activation Energy)
                          </h4>
                          <div className="bg-black border border-zinc-800 p-4 rounded mb-4 font-mono text-center text-zinc-400 text-sm">
                              k = A · e<sup>-Ea/RT</sup>
                          </div>
                          <p className="text-sm md:text-base text-zinc-400 leading-7 text-justify">
                              任何现状的改变（如创业、转型）都视为一次“化学反应”。<strong>E<sub>a</sub></strong> 是打破旧平衡所需的最小能量阈值（资金、认知、人脉）。若势能壁垒远高于能量储备，强行跃迁将导致系统耗散崩溃 (System Collapse)。
                          </p>
                      </section>

                      {/* 第三定律 */}
                      <section>
                          <h4 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                              <Shield className="text-emerald-500" size={20}/> 第三定律：鲁棒性 (Robustness)
                          </h4>
                          <p className="text-sm md:text-base text-zinc-400 leading-7 text-justify">
                              低鲁棒性系统处于<strong>亚稳态 (Metastable)</strong>，微小的扰动（黑天鹅事件）即可引发灾难性相变。最优解往往不是收益最大化，而是寻找“低熵-低能耗-高稳态”的吸引子路径 (Attractor Path)。
                          </p>
                      </section>
                  </div>

                  {/* 底部引用 */}
                  <div className="pt-8 border-t border-zinc-800 text-center">
                      <p className="text-xs text-zinc-600 font-mono uppercase tracking-widest">
                          Designed by TDFT Research Lab © 2025
                      </p>
                  </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="z-10 w-full max-w-xl flex flex-col items-center gap-10">
        
        {/* ==================== 状态：空闲 ==================== */}
        {status === 'idle' && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="w-full space-y-8 text-center px-2">
             
             <div className="relative">
                <h1 className="text-5xl md:text-6xl font-black tracking-widest text-white drop-shadow-[0_0_35px_rgba(255,255,255,0.6)]">
                    决策推演
                </h1>
                <div className="mt-4 flex justify-center gap-6 text-[10px] font-bold tracking-[0.4em] text-cyan-400/80 uppercase">
                    <span>Analysis</span>
                    <span className="text-purple-400">Logic</span>
                    <span>Entropy</span>
                </div>
             </div>
              
              <div className="space-y-5 mt-8">
                  <div className="group relative">
                      <div className="absolute -inset-0.5 bg-gradient-to-r from-cyan-500 to-blue-500 rounded-lg opacity-20 group-focus-within:opacity-100 transition duration-500 blur"></div>
                      <div className="relative flex items-center bg-black border border-zinc-800 rounded-lg p-1">
                          <div className="w-16 h-12 flex items-center justify-center text-cyan-400 border-r border-zinc-800 font-bold text-xs shrink-0 bg-zinc-900/50 rounded-l">现状</div>
                          <input type="text" value={q1} onChange={(e) => setQ1(e.target.value)} placeholder="你现在的困境..." className="w-full bg-transparent p-3 text-white placeholder:text-zinc-600 outline-none font-medium text-base" />
                      </div>
                  </div>

                  <div className="group relative">
                      <div className="absolute -inset-0.5 bg-gradient-to-r from-purple-500 to-pink-500 rounded-lg opacity-20 group-focus-within:opacity-100 transition duration-500 blur"></div>
                      <div className="relative flex items-center bg-black border border-zinc-800 rounded-lg p-1">
                          <div className="w-16 h-12 flex items-center justify-center text-purple-400 border-r border-zinc-800 font-bold text-xs shrink-0 bg-zinc-900/50 rounded-l">方案</div>
                          <input type="text" value={q2} onChange={(e) => setQ2(e.target.value)} placeholder="你想怎么做..." className="w-full bg-transparent p-3 text-white placeholder:text-zinc-600 outline-none font-medium text-base" />
                      </div>
                  </div>

                  <div className="group relative">
                      <div className="absolute -inset-0.5 bg-gradient-to-r from-emerald-500 to-green-500 rounded-lg opacity-20 group-focus-within:opacity-100 transition duration-500 blur"></div>
                      <div className="relative flex items-center bg-black border border-zinc-800 rounded-lg p-1">
                          <div className="w-16 h-12 flex items-center justify-center text-emerald-400 border-r border-zinc-800 font-bold text-xs shrink-0 bg-zinc-900/50 rounded-l">约束</div>
                          <input type="text" value={q3} onChange={(e) => setQ3(e.target.value)} placeholder="最坏的结果..." className="w-full bg-transparent p-3 text-white placeholder:text-zinc-600 outline-none font-medium text-base" />
                      </div>
                  </div>
              </div>

              <button onClick={startAnalysis} className="group relative w-full py-5 bg-white text-black font-black text-lg tracking-widest rounded-xl hover:scale-[1.02] transition-transform shadow-[0_0_30px_rgba(255,255,255,0.4)]">
                 <div className="flex items-center justify-center gap-3">
                    <Fingerprint className="group-hover:text-purple-600 transition-colors" size={24}/> 
                    启动推演程序
                 </div>
              </button>
          </motion.div>
        )}

        {status === 'analyzing' && (
           <div className="flex flex-col items-center gap-8 py-20">
              <div className="relative w-32 h-32">
                 <div className="absolute inset-0 border-4 border-zinc-800 rounded-full"></div>
                 <div className="absolute inset-0 border-4 border-t-cyan-400 border-r-transparent border-b-transparent border-l-transparent rounded-full animate-spin"></div>
                 <div className="absolute inset-4 border-4 border-t-purple-500 border-r-transparent border-b-transparent border-l-transparent rounded-full animate-spin-reverse"></div>
                 <div className="absolute inset-0 flex items-center justify-center animate-pulse">
                    <Atom className="text-white" size={32}/>
                 </div>
              </div>
              <p className="text-cyan-400 text-xs font-mono tracking-[0.3em] animate-pulse">SYSTEM PROCESSING...</p>
           </div>
        )}

        {status === 'result' && result && (
           <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="w-full space-y-6 pb-20">
              
              <div className="bg-zinc-900/60 border border-zinc-700/50 backdrop-blur-md p-6 md:p-8 rounded-2xl relative overflow-hidden">
                 <div className="absolute top-0 right-0 p-4 opacity-10"><Sparkles size={64}/></div>
                 
                 <div className="flex justify-between items-end mb-6">
                    <div>
                        <span className="text-zinc-500 font-bold text-[10px] tracking-widest uppercase block mb-1">Success Probability</span>
                        <span className="text-5xl font-black text-white drop-shadow-[0_0_10px_rgba(255,255,255,0.5)]">{result.probability_score}%</span>
                    </div>
                    <div className={`px-3 py-1 rounded text-xs font-bold ${result.probability_score > 60 ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'}`}>
                        {result.probability_score > 60 ? 'RECOMMENDED' : 'HIGH RISK'}
                    </div>
                 </div>

                 <div className="w-full h-3 bg-black rounded-full overflow-hidden mb-3 border border-zinc-800">
                    <motion.div 
                        initial={{ width: 0 }} 
                        animate={{ width: `${result.probability_score}%` }}
                        className={`h-full ${getProbabilityColor(result.probability_score)}`} 
                    />
                 </div>

                 <div className="flex justify-between text-[10px] text-zinc-500 font-mono tracking-wider mb-8">
                    <span className="flex items-center gap-1"><span className="w-2 h-2 bg-red-500 rounded-full"></span> 0-40% 劝退</span>
                    <span className="flex items-center gap-1"><span className="w-2 h-2 bg-cyan-500 rounded-full"></span> 40-75% 观望</span>
                    <span className="flex items-center gap-1"><span className="w-2 h-2 bg-emerald-500 rounded-full"></span> 75%+ 推荐</span>
                 </div>
                 
                 <div className="space-y-8">
                     <div>
                         <h3 className="text-sm font-bold text-cyan-500 tracking-widest uppercase mb-3 flex items-center gap-2"><Microscope size={16}/> 物理模型诊断</h3>
                         <p className="text-base text-white font-bold leading-relaxed">{result.conclusion}</p>
                     </div>

                     {result.vernacular && (
                         <div className="bg-white/5 border border-white/10 rounded-lg p-5 relative overflow-hidden">
                             <div className="absolute top-0 left-0 w-1 h-full bg-yellow-500"></div>
                             <h3 className="text-sm font-bold text-yellow-500 tracking-widest uppercase mb-3 flex items-center gap-2"><MessageSquare size={16}/> 深度解码 (Core Insight)</h3>
                             <p className="text-sm md:text-base text-zinc-200 leading-relaxed italic">"{result.vernacular}"</p>
                         </div>
                     )}

                     <div className="h-px bg-zinc-800 w-full"></div>
                     
                     <div>
                         <h3 className="text-sm font-bold text-emerald-500 tracking-widest uppercase mb-3 flex items-center gap-2"><Zap size={16}/> 优化策略</h3>
                         <p className="text-zinc-400 text-sm leading-7">{result.suggestion}</p>
                     </div>
                 </div>
              </div>

              <div className="flex gap-0 border border-zinc-700 rounded-xl overflow-hidden shadow-lg">
                 <input 
                    type="text" 
                    value={supplement} 
                    onChange={e => setSupplement(e.target.value)} 
                    placeholder="觉得不准？输入补充信息..." 
                    className="flex-grow bg-zinc-900 p-4 text-sm text-white placeholder:text-zinc-600 outline-none" 
                    onKeyDown={(e) => e.key === 'Enter' && submitSupplement()}
                 />
                 <button onClick={submitSupplement} className="bg-white text-black px-6 font-bold hover:bg-zinc-200 transition-colors"><Send size={18}/></button>
              </div>

              <button onClick={() => {setStatus('idle'); setQ1(''); setQ2(''); setQ3('');}} className="w-full py-4 text-zinc-500 text-xs font-bold tracking-widest hover:text-white transition-colors flex items-center justify-center gap-2">
                 <Cpu size={12}/> 重置系统 (RESET)
              </button>
           </motion.div>
        )}

      </div>
      
      <style jsx global>{`
        .custom-scrollbar::-webkit-scrollbar { width: 4px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: #000; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #333; }
        .animate-spin-reverse { animation: spin 12s linear infinite; }
        @keyframes spin-reverse { from { transform: rotate(360deg); } to { transform: rotate(0deg); } }
      `}</style>
    </main>
  );
}